application: hpajaxrpc
version: 1
runtime: python
api_version: 1

# use versioning on static resources if they become stale,
# e.g. /img/version_num/image.png .
default_expiration: "365d"

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /hpajaxrpc\.js
  static_files: hpajaxrpc.js
  upload: hpajaxrpc\.js

- url: /.+
  script: main.py
