application: hpajaxrpc
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /hpajaxrpc\.js
  static_files: hpajaxrpc.js
  upload: hpajaxrpc\.js

- url: /.+
  script: main.py
